@startuml
allowmixing

actor Kunde
actor Fahrer
actor Flottenmanager

object EasyRideSystem

Kunde -left-> EasyRideSystem : Buchen/Stornieren einer Fahrt


EasyRideSystem --> Fahrer : Erhält Informationen über \n Abhol- und Zielort \n und Name \n des Kunden
Fahrer --> EasyRideSystem : Erreichen des \n nächsten Haltepunktes bestätigen
Flottenmanager -> EasyRideSystem : Daten abruf
@enduml