@startuml
allowmixing

actor Kunde
actor Fahrer
actor Flottenmanager

object Kundensystem
object Firmensystem

Kunde -left-> Kundensystem : Buchen/Stornieren einer Fahrt



Fahrer --> Kunde : Erhält Informationen über \n Abhol- und Zielort \n und Name \n des Kunden
Fahrer -left-> Firmensystem : Erreichen des \n nächsten Haltepunktes bestätigen
Flottenmanager -left> Kundensystem : Daten abruf
Flottenmanager -> Firmensystem : Daten abruf
Firmensystem <-right-> Kundensystem : Datenaustausch
@enduml