@startuml

start

:App Öffnen;

:Zeitpunkt eingeben;
:Haltepunkte eingeben;
:Fahrt bestätigen;

if (Zahlungsmethode hinzufügen?) is (Ja) then
    :Fahrt endgültig buchen;
else (Nein)

endif


stop

@enduml



@enduml
