@startuml
|Kundenfrontend|
start
:App Öffnen;

:App Einstellungen;
:Mein Konto;
:Kontoeinstellungen;
:Account löschen;
|Kundenfrontend|

if (Wollen Sie ihr Konto löschen?) is (yes) then
|Datenkomp.|
  :Konto aus Datenbank löschen;
else (no)
endif
|Kundenfrontend|
stop

@enduml


@enduml
