@startuml
'https://plantuml.com/activity-diagram-beta
'Kunde bucht für eine andere Person eine Fahrt.
|Kundenfrontend|
start

'Frontend
:App öffnen;
'Datenkom
|Datenkomponente|
:Meine Fahrten;

'Frontend
|Kundenfrontend|
:Gebuchte Fahrt auswählen;
if (Fahrt stornieren?) is (yes) then
else (no)
    stop
endif

split
    |Technische Komp.|
 :Fahrt stornieren fehlgeschlagen;
 split again
 |Fachliche Komp.|
   :Fahrt stornieren erfolgreich;

   |Prozess Komp.|
   :Update Routen;

end split
stop

@enduml
