package Vorlesungen.Woche1;

public enum Genre {
    ACTION, ADVENTURE, ROMANCE, HORROR,
    SCIENCEFICTION, FANTASY, THRILLER, MYSTERY,
    HISTORICALFICTION, CRIME, COMEDY, DRAMA,
    WESTERN, BIOGRAPHY, AUTOBIOGRAPHY, SATIRE,
    FABLE, FAIRYTALE, POETRY, NONFICTION

}
